apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: service
  name: service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8000 # containerized app's server port
    nodePort: 30726
    protocol: TCP
    name: http
  selector:
    io.kompose.service: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: service
  name: service
spec:
  selector:
    matchLabels:
      io.kompose.service: service
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: service
    spec:
      containers:
      - env:
        - name: MONGO_URI
          value: mongodb://mongo:27017
        name: service
        imagePullPolicy: Always
        image: li54/student_service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}